# Generated by Django 3.0.3 on 2020-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('campaign_id', models.TextField()),
                ('auto_fb_post_mode', models.BooleanField()),
                ('category_id', models.TextField()),
                ('currencycode', models.TextField()),
                ('current_amount', models.TextField()),
                ('goal', models.TextField()),
                ('donators', models.TextField()),
                ('days_active', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('has_beneficiary', models.BooleanField()),
                ('turn_off_donations', models.BooleanField()),
                ('user_id', models.TextField()),
                ('user_first_name', models.TextField()),
                ('visible_in_search', models.BooleanField()),
                ('deactivated', models.BooleanField()),
                ('campaign_image_url', models.TextField()),
                ('launch_date', models.TextField()),
                ('campaign_hearts', models.TextField()),
                ('social_share_total', models.TextField()),
                ('social_share_last_update', models.TextField()),
                ('location_city', models.TextField()),
                ('location_country', models.TextField()),
                ('is_charity', models.BooleanField()),
                ('charity_valid', models.BooleanField()),
                ('charity_name', models.TextField(null=True)),
            ],
        ),
    ]
