# Generated by Django 3.0.5 on 2020-04-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200406_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='auto_fb_post_mode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_hearts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='charity_valid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='days_active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deactivated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='donators',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='has_beneficiary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_charity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='launch_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_share_last_update',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_share_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='turn_off_donations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='visible_in_search',
            field=models.TextField(),
        ),
    ]
